server:
  port: 8080
  host: "localhost"

db:
  url: "postgresql://postgres:12345678@localhost:5432/library"

gorm:
  db

migration:
  path: "./migrations"
  url: "postgresql://postgres:12345678@localhost:5432/library?sslmode=disable"

redis:
  addr: "localhost:6379"
  password: "1234"
  db: 0

app:
  secret: "c2Zhc2VjZ2hocmdqaGRmREFGWkRGSEVSUVdSRnNhZGFzZGFzZEFE"
